[package]
name = "invincible"
version = "0.1.0"
authors = ["RichoDemus <git@richodemus.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.23.0"
rand = { version = "0.7.3", features = ["stdweb"] }
quicksilver = { version = "0.4.0", default-features = true, features = ["stdweb"]}
ncollide2d = "0.26.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
uuid = { version = "0.8", features = ["v4"] }
